TARGET_BOOTLOADER_BOARD_NAME := picasso

TARGET_BOARD_PLATFORM := tegra3

TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := true
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_ARCH_VARIANT_CPU := cortex-a9
TARGET_CPU_VARIANT := cortex-a9

TARGET_NO_BOOTLOADER := true

BOARD_KERNEL_CMDLINE := androidboot.hardware=picasso
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048

TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

BOARD_BOOTIMAGE_PARTITION_SIZE := 8388608
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 6291456
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1283457024
BOARD_CACHEIMAGE_PARTITION_SIZE := 367001600
BOARD_USERDATAIMAGE_PARTITION_SIZE := 29813112832
BOARD_FLASH_BLOCK_SIZE := 4096

TARGET_KERNEL_SOURCE := kernel/nvidia/tegra3
TARGET_KERNEL_CONFIG := picasso_recovery_defconfig

BOARD_CUSTOM_BOOTIMG_MK := device/acer/picasso2/custombootimg.mk

# Recovery
TARGET_RECOVERY_FSTAB := device/acer/picasso2/twrp.fstab
BOARD_HAS_NO_SELECT_BUTTON := true

# TWRP
TW_THEME := landscape_hdpi
RECOVERY_SDCARD_ON_DATA := true
TW_CUSTOM_BATTERY_PATH := /sys/class/power_supply/bq27541-0
TARGET_RECOVERY_FORCE_PIXEL_FORMAT := RGB_565

# TWRP hacks to reduce ramdisk size
#TW_EXCLUDE_ENCRYPTED_BACKUPS := true
#TW_EXCLUDE_SUPERSU := true
#TW_NO_EXFAT := true
